import type { Metadata } from 'next';
import { Inknut_Antiqua } from 'next/font/google';
import './globals.css';
import { RmLayout } from '@/components/RmLayout';

const inknutAntiqua = Inknut_Antiqua({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inknutAntiqua.className} h-[100dvh] overflow-y-auto antialiased`}
				cz-shortcut-listen="true"
			>
				<RmLayout>{children}</RmLayout>
			</body>
		</html>
	);
}
